env_param:
  lift_distance: 0.1
  drop_distance: 0.2
  conveyor_velocity: 1.0
  conveyor_power: 0.15
  conveyor_belt_length: 2.7

pose_timer:
  approach_time: -3.0
  pick_time: 0
  retreat_time: 3.0
  place_time: 7.0

pick_offset:
  gear_part:
    offset: 
      xyz: [0.0, -0.05, -0.046094] #0.9220
      rpy: [0.0, 0.0, 0.0] 
  piston_rod_part:
    offset: 
      xyz: [0.0, 0.0, -0.045094] #0.8883
      rpy: [0.0, 0.0, 0.0] 
  pulley_part:
    offset: 
      xyz: [0.00, 0.00, -0.018594] #0.941
      rpy: [0.0, 0.0, 0.0] 
  gasket_part:
    offset: 
      xyz: [0.0, 0.0, -0.0482] #0.9087
      rpy: [0.0, 0.0, 0.0] 
  disk_part:
    offset: 
      xyz: [0.0, -0.20, -0.049994] #0.9453 -0.035994
      rpy: [0.0, 0.0, 0.0] 

bin_origin:
  gasket_part:
    pose:
      xyz: [-0.3, 1.2, 1.1]
      rpy: [0, 0, 0]
  piston_rod_part:
    pose:
      xyz: [-0.3, 0.4, 1.1]
      rpy: [0, 0, 0]
  gear_part:
    pose:
      xyz: [-0.3, -0.4, 1.1]
      rpy: [0, 0, 0]
  disk_part:
    pose:
      xyz: [-0.3, -1.2, 1.1]
      rpy: [0, 0, 0]
  pulley_part:
    pose:
      xyz: [-0.3, -2.0, 1.1]
      rpy: [0, 0, 0]

robot_origin:
  pose:
    xyz: [1.0, 0.0, 0.0]
    rpy: [0, 0, 0]   
